version = 1

exclude_patterns = [
  "node_modules/",
  "dist/",
  "build/",
  "public/assets/",
  "**/*.min.js",
  "**/*.min.css",
  "coverage/"
]

test_patterns = [
  "tests/**",
  "**/__tests__/**",
  "**/*.test.js",
  "**/*.test.ts",
  "**/*.spec.js",
  "**/*.spec.ts"
]

# JavaScript/TypeScript analyzer
[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = ["browser", "nodejs"]
  plugins = ["react"]
  style_guide = "standard"
  dialect = "typescript"

# Python analyzer (if applicable)
[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"

# Code transformers
[[transformers]]
name = "prettier"
enabled = true

[[transformers]]
name = "eslint"
enabled = true
