version = 1
test_patterns = [
  "tests/**",
  "**/__tests__/**",
  "**/*.test.js",
  "**/*.test.ts",
  "**/*.spec.js",
  "**/*.spec.ts"
]
exclude_patterns = [
  "node_modules/",
  "dist/",
  "build/",
  "public/assets/",
  "**/*.min.js",
  "**/*.min.css",
  "coverage/"
]

[[analyzers]]
name = "javascript"

[analyzers.meta]
plugins = [ "vue" ]
environment = [
  "browser",
  "nodejs"
]
